default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: qwerty
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_gateway_development

test:
  <<: *default
  database: api_gateway_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>