default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_gateway_development

test:
  <<: *default
  database: api_gateway_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>